openapi: 3.0.0
info:
  title: api
  version: '2.0'
servers:
  - url: 'http://localhost:5000'
paths:
  /running:
    get:
      summary: Get current status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  isRunning:
                    type: boolean
      operationId: get-running
    put:
      summary: Set current status
      tags: []
      responses:
        '200':
          description: OK
      operationId: put-running
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                isRunning:
                  type: boolean
  /humidity:
    get:
      summary: Get current humidity
      tags: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  humidity:
                    type: integer
          description: ''
      operationId: get-humidity
    put:
      summary: Set humidity to achieve
      tags: []
      operationId: put-humidity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                humidity:
                  type: integer
      responses:
        '200':
          description: OK
  /waterlevel:
    get:
      summary: Get current water level
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  waterLevel:
                    type: integer
      operationId: get-waterlevel
  /chargelevel:
    get:
      summary: Get current charge level
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  chargeLevel:
                    type: integer
      operationId: get-chargelevel
  /wateringtime_from:
    get:
      summary: Get the allowed watering time
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  wateringTimes:
                    type: object
                    properties:
                        from:
                          type: string
      operationId: get-wateringtime_from
    put:
      summary: Set the allowed watering time
      tags: []
      responses:
        '200':
          description: OK
      operationId: put-wateringtime_from
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                wateringTimes:
                  type: object
                  properties:
                      from:
                        type: string
  /wateringtime_to:
    get:
      summary: Get the end of allowed watering time
      tags: []
      responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    wateringTimes:
                      type: object
                      properties:
                          from:
                            type: string
      operationId: get-wateringtime_to
    put:
      summary: Set the end of allowed watering time
      tags: []
      responses:
        '200':
          description: OK
      operationId: put-wateringtime_to
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                wateringTimes:
                  type: object
                  properties:
                      to:
                        type: string
components:
  schemas: {}
